'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameEngine,TYPES,GRID,coord,parseCoord,newProfile,cleanProfile,buy,reward,dist}=require('../dist/js/engine.js');
const game=(mission=0,type='destroyer')=>{const g=new GameEngine(427);g.start(mission,'normal',[{id:'local',name:'Captain',type,upgrades:{}}]);return g;};
function quiet(g){g.state.islands=[];for(const s of g.state.ships){if(!s.owner)s.owner='test-'+s.id;s.input={throttle:0,steer:0};s.gunCD=999;s.jumpCD=999;s.droneCD=999;s.dest=null;}g.selected.gunCD=0;}
function advance(g,seconds){for(let i=0;i<seconds/.05;i++)g.tick(.05);}
function enemyNear(g,d=6){const p=g.selected,e=g.state.ships.find(s=>s.team==='enemy');e.x=p.x;e.y=p.y-d;e.heading=0;e.velocity=0;g.reveal(e,100);g.setTarget(e.x,e.y);return e;}
test('larger map and five playable hulls',()=>{assert.equal(GRID,36);for(const t of ['destroyer','frigate','torpedo','cruiser','battleship'])assert(TYPES[t].hp>0);});
test('only one human-controlled ship in solo, AI fills other slots',()=>{const g=game();assert.equal(g.state.ships.filter(s=>s.owner==='local').length,1);assert.equal(g.state.ships.filter(s=>s.team==='player'&&!s.owner).length,3);assert.equal(typeof g.select,'undefined');});
test('co-op roster gives each player exactly one distinct ship',()=>{const g=game();g.start(0,'normal',[{id:'a',name:'A',type:'frigate'},{id:'b',name:'B',type:'cruiser'}]);assert.notEqual(g.forOwner('a').id,g.forOwner('b').id);assert.equal(g.forOwner('b').type,'cruiser');});
test('paused simulation freezes physics, cooldowns and shots',()=>{const g=game(),time=g.state.time,y=g.selected.y;g.input(g.selected.id,{throttle:1,steer:1});advance(g,2);assert.equal(g.state.time,time);assert.equal(g.selected.y,y);});
test('throttle accelerates gradually and stopped engines retain inertia',()=>{const g=game();quiet(g);const p=g.selected;g.state.running=true;for(let i=0;i<70;i++){g.input(p.id,{throttle:1,steer:0});g.tick(.05);}assert(p.velocity>0&&p.velocity<p.speed);const old=p.velocity;g.action('stop');g.input(p.id,{throttle:0,steer:0});g.tick(.05);assert(p.velocity>0&&p.velocity<old);});
test('rudder turns ship with roll, not teleportation',()=>{const g=game();quiet(g);g.state.running=true;const p=g.selected,h=p.heading;let maxRoll=0;for(let i=0;i<80;i++){g.input(p.id,{throttle:1,steer:1});g.tick(.05);maxRoll=Math.max(maxRoll,Math.abs(p.roll));}assert(p.heading>h);assert(maxRoll>.005);});
test('island collision prevents crossing land',()=>{const g=game();quiet(g);const p=g.selected;g.state.islands=[{x:p.x,y:p.y-1,r:.7,h:1}];p.throttle=1;p.velocity=1;p.vy=-1;g.state.running=true;advance(g,2);assert(dist(p,g.state.islands[0])>.7);});
test('range validation and turret rotation precede firing',()=>{const g=game();quiet(g);g.setTarget(35,1);assert(!g.action('gun').ok);g.setTarget(g.selected.x+4,g.selected.y);assert(!g.action('gun').ok);g.state.running=true;advance(g,2);assert(g.action('gun').ok);assert(!g.action('gun').ok);});
test('shell follows a raised ballistic arc and damages a stationary target',()=>{const g=game();quiet(g);const e=enemyNear(g);assert(g.action('gun').ok);g.state.running=true;advance(g,.7);assert(g.state.projectiles[0].z>.6);const hp=e.hp;advance(g,3);assert(e.hp<hp);});
test('multiple locks require acquisition time and allocate one missile each',()=>{const g=game();quiet(g);const p=g.selected,e=enemyNear(g),e2=g.state.ships.filter(x=>x.team==='enemy')[1];e2.x=p.x+2;e2.y=p.y-6;g.reveal(e2,20);assert(g.action('lock',p.id,{targetId:e.id}).ok);assert(g.action('lock',p.id,{targetId:e2.id}).ok);assert(!g.action('missile').ok);g.state.running=true;advance(g,1.1);const before=p.missiles;assert(g.action('missile').ok);assert.equal(p.missiles,before-2);assert.equal(new Set(g.state.projectiles.map(x=>x.targetId)).size,2);});
test('lock capacity and visibility are enforced',()=>{const g=game();quiet(g);const p=g.selected,e=enemyNear(g);p.lockLimit=1;g.action('lock',p.id,{targetId:e.id});const e2=g.state.ships.filter(x=>x.team==='enemy')[1];e2.x=p.x+1;e2.y=p.y-6;g.reveal(e2,20);assert(!g.action('lock',p.id,{targetId:e2.id}).ok);g.action('clearLocks');e.visibleUntil=-1;assert(!g.action('lock',p.id,{targetId:e.id}).ok);});
test('guided missile accelerates, curves and hits',()=>{const g=game();quiet(g);const e=enemyNear(g);g.action('lock',g.selected.id,{targetId:e.id});g.state.running=true;advance(g,1.1);g.action('missile');advance(g,.2);assert(g.state.projectiles[0].speed<5.6);e.x+=1;const hp=e.hp;advance(g,7);assert(e.hp<hp);});
test('torpedoes move beneath the surface and do damage',()=>{const g=game(0,'torpedo');quiet(g);const e=enemyNear(g,4),hp=e.hp;assert(g.action('torpedo').ok);g.state.running=true;advance(g,.2);assert(g.state.projectiles[0].z<0);advance(g,4);assert(e.hp<hp);});
test('battleships cannot fire torpedoes',()=>{const g=game(2,'battleship');enemyNear(g);assert(!g.action('torpedo').ok);});
test('jumping alien leaves water, relocates and splashes down',()=>{const g=game();quiet(g);const e=enemyNear(g),start={x:e.x,y:e.y};g.jump(e);assert(e.jump);g.state.running=true;advance(g,2.2);assert(e.heave>1);advance(g,2);assert.equal(e.jump,null);assert(dist(e,start)>3);assert(g.state.effects.some(f=>f.kind==='splash'));});
test('destroyed targets are removed from locks and from world after animation',()=>{const g=game();quiet(g);const e=enemyNear(g);g.action('lock',g.selected.id,{targetId:e.id});g.damage(e,9999,'player');assert(!g.selected.locks.includes(e.id));assert.equal(g.state.stats.kills,1);g.damage(e,999,'player');assert.equal(g.state.stats.kills,1);g.state.running=true;advance(g,4);assert(!g.state.ships.some(s=>s.id===e.id));});
test('last destroyed target also disappears on victory',()=>{const g=game();for(const e of g.state.ships.filter(x=>x.team==='enemy'))g.damage(e,99999,'player');g.checkEnd();assert(g.state.ended.win);assert(!g.state.ships.some(x=>x.hp<=0));});
test('defense intercepts approaching missile',()=>{const g=game();quiet(g);const e=enemyNear(g,6),p=g.selected,hp=p.hp;g.action('defense');g.launch(e,p,'missile',200,p.id);g.state.running=true;advance(g,4);assert.equal(p.hp,hp);assert(g.state.stats.intercepts>0);});
test('repair consumes kit and restores 35 percent over time',()=>{const g=game();quiet(g);const p=g.selected;p.hp=p.maxHP*.2;g.action('repair');assert.equal(p.repairs,2);g.state.running=true;advance(g,11);assert(p.hp>p.maxHP*.54&&p.hp<p.maxHP*.56);});
test('battleship anchor boosts aggregate broadside once',()=>{const g=game(2,'battleship');quiet(g);enemyNear(g);g.action('anchor');g.action('gun');assert.equal(Math.round(g.state.projectiles.reduce((a,p)=>a+p.damage,0)),Math.round(g.selected.damage*1.7));assert.equal(g.selected.boostUntil,0);});
test('AI allies maneuver and fire without player input',()=>{const g=game();g.state.running=true;const ally=g.state.ships.find(p=>p.team==='player'&&!p.owner),start={x:ally.x,y:ally.y};advance(g,35);assert(dist(ally,start)>.5);assert(g.state.stats.shots>0);});
test('protect ATLAS and destroy generator before uplink',()=>{const g=game(1);g.damage(g.state.ships.find(x=>x.type==='support'),99999,'enemy');g.checkEnd();assert(!g.state.ended.win);const h=game(2),u=h.state.ships.find(s=>s.type==='uplink'),shield=h.state.ships.find(s=>s.type==='shield'),hp=u.hp;h.damage(u,100,'player');assert.equal(u.hp,hp);h.damage(shield,9999,'player');h.damage(u,100,'player');assert(u.hp<hp);});
test('shop debits credits once and clamps upgrade levels',()=>{const p=cleanProfile(newProfile());assert(buy(p,'upgrade','armor').ok);assert.equal(p.credits,750);assert.equal(p.upgrades.destroyer.armor,1);assert(!buy(p,'ship','battleship').ok);p.credits=100000;for(let i=0;i<5;i++)buy(p,'upgrade','armor');assert.equal(p.upgrades.destroyer.armor,4);assert(buy(p,'ship','cruiser').ok);const bal=p.credits;assert(!buy(p,'ship','cruiser').ok);assert.equal(p.credits,bal);});
test('upgrades change actual vessel stats',()=>{const g=game(),base=g.selected;const stronger=g.ship('destroyer','player','test',2,2,'other',{armor:2,missile:2,engine:2,locks:2});assert(stronger.maxHP>base.maxHP);assert(stronger.missileDamage>base.missileDamage);assert.equal(stronger.lockLimit,4);});
test('match reward is deduplicated and unlocks next mission',()=>{const g=game(),p=newProfile();g.end(true,'test');const a=reward(p,g.state);assert(a>0);assert.equal(reward(p,g.state),0);assert.equal(p.unlockedMission,1);});
test('save restores complete simulation paused; malformed data rejected atomically',()=>{const g=game();g.state.running=true;advance(g,2);const s=g.export(),h=game();assert(h.import(s));assert.equal(h.state.time,g.state.time);assert(!h.state.running);const current=h.state,bad=JSON.parse(s);bad.state.ships[0].velocity='bad';assert(!h.import(JSON.stringify(bad)));assert.equal(h.state,current);assert(!h.import('{}'));});
test('public snapshots conceal unrevealed enemy positions',()=>{const g=game(),e=g.state.ships.find(x=>x.team==='enemy');e.visibleUntil=-1;const snap=g.publicSnapshot();assert(!snap.ships.some(x=>x.id===e.id));assert(g.state.ships.some(x=>x.id===e.id));});
test('expanded grid coordinate round trips',()=>{assert.equal(coord(35.5,35.5),'AJ36');assert.deepEqual(parseCoord('AJ36'),{x:35.5,y:35.5});assert.deepEqual(parseCoord('AA1'),{x:26.5,y:.5});assert.equal(parseCoord('AK1'),null);assert.equal(parseCoord('A0'),null);});
